using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class PlaneController : MonoBehaviour
{
    [Header("Plane stats")]
    [Tooltip("How much the throttle ramps up or down.")]
    public float throttleIncrement = 1f;
    [Tooltip("Maximum engine thrust when at 100% throttle.")]
    public float maxThrust = 700f;
    [Tooltip("How responsive the plane is when rolling, pitching and yawing.")]
    public float responsiveness = 30f;

    [Tooltip("How much lift force this plane generates as it gains speed.")]
    public float lift = 135f;

    [Tooltip("Explosion model.")]
    [SerializeField] private GameObject _explosion;
    private float time = 0f;
    private float timeDelay = 2f;
    private int counter = 1;

    private float throttle;     // Percentage of maximum engine thrust currently being used.
    private float roll;         // Tilting left to right.
    private float pitch;        // Tilting front to back.
    private float yaw;          // "Turning" left to rigth.

    public GameObject eksplozija1;
    public GameObject eksplozija2;

    private float responseModifier { // Value used to tweak responsiveness to suit plane's mass.
        get {
            return (rb.mass / 10f) * responsiveness;
        }
    }

    Rigidbody rb;
    [SerializeField] TextMeshProUGUI hud;

    // Start is called before the first frame update
    private void Start() // Awake()
    {
        rb = GetComponent<Rigidbody>();
    }

    private void OnTriggerStay()
    {
        if (time >= timeDelay)
        {
            Vector3 explosionPosition;
            if (counter == 1)
            {
                explosionPosition = eksplozija1.transform.position;
                counter = 0;
                
            }
            else
            {
                explosionPosition = eksplozija2.transform.position;
                counter = 1;
            }
            Instantiate(_explosion, explosionPosition, Quaternion.identity);
            time = 0;
        }

    }

    private void HandleInputs() 
    {
        // Set rotational values from our axis inputs
        roll = Input.GetAxis("Roll");
        pitch = Input.GetAxis("Pitch");
        yaw = Input.GetAxis("Yaw");

        // Handle throttle value being sure to clamp it between 0 and 100.
        if (Input.GetKey(KeyCode.LeftShift)) throttle += throttleIncrement;
        else if (Input.GetKey(KeyCode.Space)) throttle -= throttleIncrement;
        throttle = Mathf.Clamp(throttle, 0f, 100f);
    }

    // Update is called once per frame
    private void Update()
    {
        time = time + 1f * Time.deltaTime;
        
        if (!PauseMenu.isPaused){
        HandleInputs();
        UpdateHUD();
        }
    }

    private void FixedUpdate()
    {
        // Apply forces to our plane
        rb.AddForce(transform.forward * maxThrust * throttle);
        rb.AddTorque(transform.up * yaw * responseModifier);
        rb.AddTorque(transform.right * pitch * responseModifier);
        rb.AddTorque(transform.forward * roll * responseModifier);

        // adding upward draft force
        rb.AddForce(Vector3.up * rb.velocity.magnitude * lift);
    }

    private void UpdateHUD() 
    {
        hud.text = "Throttle " + throttle.ToString("F0") + "%\n";
        hud.text += "Airspeed: " + (rb.velocity.magnitude * 3.6f).ToString("F0") + "km/h\n";
        hud.text += "Altitude: " + transform.position.y.ToString("F0") + "m\n";
    }

}
